{% set version = "2.14.0" %}

package:
  name: proliantutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/proliantutils/proliantutils-{{ version }}.tar.gz
  sha256: 9251116fde90ede255d240702c8eefa554d609b5db013d87a2d907a5c11a9aae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pbr >=2.0.0
  run:
    - python
    - pbr >=2.0.0
    - six >=1.9.0
    - oslo.concurrency >=3.8.0
    - oslo.serialization >=1.10.0
    - oslo.utils >=3.20.0
    - jsonschema >=2.6.0
    - requests !=2.12.2,!=2.13.0,>=2.10.0
    - retrying !=1.3.0,>=1.2.3
    - pysnmp >=4.2.3,<5.0.0
    - sushy >=1.8.0

test:
  imports:
    - proliantutils
    - proliantutils.exception
    - proliantutils.log
    - proliantutils.utils

about:
  home: https://github.com/openstack/proliantutils
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Proliantutils is a set of utility libraries for interfacing and managing various components (like iLO, HPSSA) for HP Proliant Servers. This library is used by iLO drivers in Ironic for managing Proliant Servers (though the library can be used by anyone who wants to manage HP Proliant servers)

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
