travis:
  secure:
    BINSTAR_TOKEN: IIX6R/1N+KbPLkIVtD/hPQIl0ic7JcUv37TnXEiQzoiVgGikdCQ3sTcRVM1onLSM565JQH+xcKxvIyjzHGo6zoW7BHcMWMteix3D4zlfnP3Yxn/itNYFY3huRG0IvQqxORRAojlweN9AZlicOdDzirq17SOOc+AbGZhjFO9zmr5TyvwwpnA1EuOUJdGnu1q8s0cFrhubt5rrpMwOXvLC7+X47SCs5/1aGksZLsm0uIg6tpJppYFv3TqOTak6wclAUlnazpMVlQmo8gPJ96g+SfdE9wEJL5O9aVzUqjS+qccsnslDfntKyt3BZMi1XubysqYt067BQu3UehoUpPWcz2ROwAg91HkJbhhNGARRjnAkulFuR50aLtvj5CN3O22SMMPeuoQb5Geuw93V9MzH+zfAW4a0TBq3Z2+bd7MidnjbjpxLg1WuzBIFNMnIyD/q4y2w5W3JG3WbTtjj6xgsjLskBVM9b4dV/5u0goETRqlEywpCXYnmWL+S/rAtV+Vav4sW8zkAiOlPUKfvL8xzPHs7ZLuYf7QD1G8JNmO6o7NS2jwfEuAPLwa55ZWmopRrYL5IXShQikbZMDGpDDU3wfrZWMUTuRCHq0oNhAMrLnFICdAzFmE/jtyXQ1FHWWMgn1jOqoCwJIJvx3573+8e8h/QMV27cZdw/a/aqizYsgs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
